/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.BranchWorkArea;

import Books.Book;
import General.Magazine;
import Librarian.Librarian;
import LibraryAppSystem.ApplicationSystem;
import LibraryAppSystem.UserAccount;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrunalipawar
 */
public class LibraryCollectionJPanel extends javax.swing.JPanel {

    private UserAccount useraccount;
    private ApplicationSystem system;
    private Librarian lib;
    DefaultTableModel bookTableModel;
    DefaultTableModel magazineTableModel;
    /**
     * Creates new form ViewCollectionJPanel
     */
    public LibraryCollectionJPanel() {
        initComponents();
    }

    LibraryCollectionJPanel(ApplicationSystem system, Librarian lib, UserAccount useraccount) {
       initComponents();
       this.system = system;
       this.useraccount = useraccount;
       this.lib=lib;
       this.bookTableModel = (DefaultTableModel) bookTable.getModel();
       this.magazineTableModel = (DefaultTableModel) magTable.getModel();
       populateBookCatelog();
       populateMagazineCatelog();
    }
    
    public void populateBookCatelog() {
        bookTableModel.setRowCount(0);
            
            ArrayList<Book> books=this.lib.getBooksDirectory().getBooklists();
            for(Book b: books){
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(b.getRegisteredDate());
                Object[] row = new Object[9];
            
                row[0] = b.getSerialNumber();
                row[1] = b.getName();
                row[2] = date;
                row[3] = b.getNoOfPages();
                row[4] = b.getTypeOfBinding();
                row[5] = b.getLanguage();
                row[6] = b.getAuthor().getAuthorName();
                row[7] = b.getGenre().getGenreName();
                row[8] = b.isIsAvailablityFlag();
                
                bookTableModel.addRow(row);
            }
        
    }
    
    public void populateMagazineCatelog() {
        magazineTableModel.setRowCount(0);
            ArrayList<Magazine> magazineList=this.lib.getMagazineDirectory().getMagazinelist();
            for(Magazine mag: magazineList){
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(mag.getRegisteredDate());
                Object[] row = new Object[6];
            
                row[0] = mag.getSerialNumber();
                row[1] = mag.getName();
                row[2] = date;
                row[3] = mag.getCompanyName();
                row[4] = mag.getIssueType();
                row[5] = mag.isIsAvailablityFlag();
                
                magazineTableModel.addRow(row);
            }
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        magTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AuthorHeaderjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Book Name", "Registraion Date", "Page No", "Binding Type", "Language", "Author", "Genre", "isAvailable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 800, 200));

        magTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Magazine Name", "Registration Date", "Company Name", "Issue Type", "isAvailable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(magTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 800, 200));

        jLabel1.setText("MAGAZINE CATELOG");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel2.setText("BOOK CATELOG");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        AuthorHeaderjLabel.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        AuthorHeaderjLabel.setText("LIBRARY MANAGEMENT SYSTEM - COLLECTION");
        add(AuthorHeaderjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 500, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorHeaderjLabel;
    private javax.swing.JTable bookTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable magTable;
    // End of variables declaration//GEN-END:variables
}
