/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author mrunalipawar
 */
public class AssignJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignJPanel
     */
    public AssignJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        insuranceAssignTable = new javax.swing.JTable();
        assignInsuranceButton = new javax.swing.JButton();
        insuranceSelectionComboBox1 = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insuranceAssignTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "APPLICANT ID", "PET NAME", "PLAN NAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(insuranceAssignTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 360, 150));

        assignInsuranceButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        assignInsuranceButton.setText("ASSIGN PLAN");
        assignInsuranceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignInsuranceButtonActionPerformed(evt);
            }
        });
        add(assignInsuranceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 130, 40));

        add(insuranceSelectionComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void assignInsuranceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignInsuranceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignInsuranceButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignInsuranceButton;
    private javax.swing.JTable insuranceAssignTable;
    private javax.swing.JComboBox insuranceSelectionComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
