/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Applicant;
import Model.Business;
import Model.Vaccine;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrunalipawar
 */
public class AssignVaccineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignVaccineJPanel
     */
    private Business business;
    DefaultTableModel vaccineTableModel;
    public Vaccine selectedVaccine;
    
    public AssignVaccineJPanel() {
        initComponents();
    }
    
    public AssignVaccineJPanel (Business business) {
        initComponents();
        this.business = business;
        this.vaccineTableModel = (DefaultTableModel) vaccineAssignTable.getModel();
        populatePetVaccinationDetails();
        populateVaccineData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vaccineAssignTable = new javax.swing.JTable();
        assignVaccineButton = new javax.swing.JButton();
        vaccineSelectionComboBox = new javax.swing.JComboBox();
        assignVaccineHeaderLabel = new javax.swing.JLabel();
        selectVaccineLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vaccineAssignTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "APPLICANT ID", "PET NAME", "PET AGE", "PET GENDER", "PET TYPE", "PLAN ID", "VACCINES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vaccineAssignTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 660, 200));

        assignVaccineButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        assignVaccineButton.setText("ASSIGN VACCINE");
        assignVaccineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignVaccineButtonActionPerformed(evt);
            }
        });
        add(assignVaccineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 160, 40));

        add(vaccineSelectionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 160, 40));

        assignVaccineHeaderLabel.setFont(new java.awt.Font("Kannada MN", 1, 20)); // NOI18N
        assignVaccineHeaderLabel.setText("ASSIGN VACCINE DETAILS ");
        add(assignVaccineHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 330, 40));

        selectVaccineLabel.setFont(new java.awt.Font("Kannada MN", 1, 14)); // NOI18N
        selectVaccineLabel.setText("Select Vaccine");
        add(selectVaccineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignVaccineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignVaccineButtonActionPerformed
        // TODO add your handling code here:

        Vaccine vaccine = (Vaccine) vaccineSelectionComboBox.getSelectedItem();

        int selectedRow = vaccineAssignTable.getSelectedRow();

        Applicant applicant = (Applicant) vaccineAssignTable.getValueAt(selectedRow, 0);

        applicant.setVaccine(vaccine);

        populateVaccineData();
    }//GEN-LAST:event_assignVaccineButtonActionPerformed

    public void populatePetVaccinationDetails () {
        vaccineSelectionComboBox.removeAllItems();
        
        for(Vaccine v: this.business.getVaccineDirectory().getVaccinelists()){
            vaccineSelectionComboBox.addItem(v);
        }
    }
    
    public void populateVaccineData () {
        
        vaccineTableModel.setRowCount(0);
        for (Applicant a: this.business.getAppDirectory().getApplicantsDirectory()){
            Object[] row = new Object[7];
            row[0] = a;
            row[1] = a.getPetDetails().getPetName();
            row[2] = a.getPetDetails().getAge();
            row[3] = a.getPetDetails().getGender();
            row[4] = a.getPetDetails().getPetType();
            row[5] = a.getPlanDetails().getPlanId();
            row[6] = a.getVaccine().getVaccineName();
            
            vaccineTableModel.addRow(row);
        
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignVaccineButton;
    private javax.swing.JLabel assignVaccineHeaderLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel selectVaccineLabel;
    private javax.swing.JTable vaccineAssignTable;
    private javax.swing.JComboBox vaccineSelectionComboBox;
    // End of variables declaration//GEN-END:variables
}
