/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Business;

/**
 *
 * @author mrunalipawar
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private Business business; 
    public NewJFrame() {
        initComponents();
        this.business = new Business();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        registerOwnerButton = new javax.swing.JButton();
        viewOwnerButton = new javax.swing.JButton();
        insurancePlanCatelogButton = new javax.swing.JButton();
        petVaccineButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerOwnerButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        registerOwnerButton.setText("Register Owner");
        registerOwnerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerOwnerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerOwnerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 40));

        viewOwnerButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewOwnerButton.setText("View Owner");
        viewOwnerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOwnerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(viewOwnerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 40));

        insurancePlanCatelogButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        insurancePlanCatelogButton.setText("Insurance Plan");
        insurancePlanCatelogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insurancePlanCatelogButtonActionPerformed(evt);
            }
        });
        jPanel1.add(insurancePlanCatelogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 40));

        petVaccineButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        petVaccineButton.setText("Pet Vaccine");
        petVaccineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petVaccineButtonActionPerformed(evt);
            }
        });
        jPanel1.add(petVaccineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 130, 40));

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerOwnerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerOwnerButtonActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CreateJPanel(this.business));
    }//GEN-LAST:event_registerOwnerButtonActionPerformed

    private void viewOwnerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOwnerButtonActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ViewJPanel(this.business));
    }//GEN-LAST:event_viewOwnerButtonActionPerformed

    private void insurancePlanCatelogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insurancePlanCatelogButtonActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new InsurancePlanJPanel(this.business));
    }//GEN-LAST:event_insurancePlanCatelogButtonActionPerformed

    private void petVaccineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petVaccineButtonActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new PetVaccineJPanel(this.business));
    }//GEN-LAST:event_petVaccineButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton insurancePlanCatelogButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton petVaccineButton;
    private javax.swing.JButton registerOwnerButton;
    private javax.swing.JButton viewOwnerButton;
    // End of variables declaration//GEN-END:variables
}
