/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Applicant;
import Model.ApplicantsDirectory;
import Model.Business;
import Model.PetDetails;
import Model.Vaccine;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrunalipawar
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Business business;
    DefaultTableModel applicantTableModel;
    public Applicant selectedApplicant;
    private PetDetails selectedPet;
    private List<String> selectedVaccines;
    public ViewJPanel() {
        initComponents();
    }

    ViewJPanel(Business business) {
        initComponents();
        this.business = business;
        this.applicantTableModel = (DefaultTableModel) applicantTable.getModel();
        //display the owner details
        displayApplicantDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreatePageHeaderLabel = new javax.swing.JLabel();
        applicationIdLabel = new javax.swing.JLabel();
        ownerFNameLabel = new javax.swing.JLabel();
        ownerLNameLabel = new javax.swing.JLabel();
        applicationDateLabel = new javax.swing.JLabel();
        applicationIdTextField = new javax.swing.JTextField();
        ownerFNameTextField = new javax.swing.JTextField();
        ownerLNameTextField = new javax.swing.JTextField();
        petHeaderLabel = new javax.swing.JLabel();
        petNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        petTypeLabel = new javax.swing.JLabel();
        petNameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        genderTextField = new javax.swing.JTextField();
        petTypeTextField = new javax.swing.JTextField();
        breedLabel = new javax.swing.JLabel();
        breedTextField = new javax.swing.JTextField();
        ViewButton = new javax.swing.JButton();
        updatePetButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        applicantTable = new javax.swing.JTable();
        dateTextField = new javax.swing.JTextField();
        deleteApplicantButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        CreatePageHeaderLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        CreatePageHeaderLabel.setText("View Owners Details  ");

        applicationIdLabel.setText("Applicantion ID");

        ownerFNameLabel.setText("Owner's First Name");

        ownerLNameLabel.setText("Owner's Last Name");

        applicationDateLabel.setText("Application Date");

        petHeaderLabel.setText("Pet");

        petNameLabel.setText("Pet Name");

        ageLabel.setText("Age");

        GenderLabel.setText("Gender");

        petTypeLabel.setText("Pet Type");

        breedLabel.setText("Breed");

        ViewButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ViewButton.setText("VIEW APPLICANT");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        updatePetButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        updatePetButton.setText("UPDATE PET");
        updatePetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePetButtonActionPerformed(evt);
            }
        });

        applicantTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "App ID", "First Name", "Last Name", "Date", "Pet Name", "Pet Age", "Pet Gender", "Pet Type", "Pet Breed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(applicantTable);

        deleteApplicantButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        deleteApplicantButton.setText("DELETE APPLICANT");
        deleteApplicantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteApplicantButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(CreatePageHeaderLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(petNameLabel)
                            .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(petTypeLabel)
                            .addComponent(breedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(applicationIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ownerFNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ownerLNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(applicationDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(petHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ownerLNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(ownerFNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(applicationIdTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateTextField))
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(breedTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(petTypeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(genderTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ageTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(petNameTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(updatePetButton)
                        .addGap(29, 29, 29)
                        .addComponent(ViewButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteApplicantButton)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(CreatePageHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ownerFNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ownerFNameLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(applicationIdLabel)
                                    .addComponent(applicationIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ownerLNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ownerLNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(applicationDateLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteApplicantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petNameLabel)
                    .addComponent(petNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(petTypeLabel))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breedLabel))
                .addGap(533, 533, 533))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = applicantTable.getSelectedRow();
        if(selectedRow >=0) {
            //we can directly fetch the applicant object from the 0th position
            selectedApplicant = (Applicant)applicantTable.getValueAt(selectedRow, 0);
            applicationIdTextField.setText(String.valueOf(selectedApplicant.getApplicationId()));
            ownerFNameTextField.setText(selectedApplicant.getFirstName());
            ownerLNameTextField.setText(selectedApplicant.getLastName());
            dateTextField.setText(selectedApplicant.getDate());
            petNameTextField.setText(selectedApplicant.getPetDetails().getPetName());
            ageTextField.setText(String.valueOf(selectedApplicant.getPetDetails().getAge()));
            genderTextField.setText(selectedApplicant.getPetDetails().getGender());
            petTypeTextField.setText(selectedApplicant.getPetDetails().getPetType());
            breedTextField.setText(selectedApplicant.getPetDetails().getBreed());
            
        }
        else{
            //No selection made by the user
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
    }//GEN-LAST:event_ViewButtonActionPerformed

    private void deleteApplicantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteApplicantButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = applicantTable.getSelectedRow();
                
         if(selectedRow >=0) {
             //we will delete teh object
             Applicant applicant  = (Applicant) applicantTable.getValueAt(selectedRow, 0);
             this.business.getAppDirectory().removeApplicant(applicant.getApplicationId());
             //this.business.getInsurancePlans().removeInsurancePlan(plan.getPlanId());
             displayApplicantDetails();
         }  
         else {
             
         }
    }//GEN-LAST:event_deleteApplicantButtonActionPerformed

    private void updatePetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePetButtonActionPerformed
        // TODO add your handling code here:
        
        applicationIdTextField.setEnabled(false);
        ownerFNameTextField.setEnabled(false);
        ownerLNameTextField.setEnabled(false);
        dateTextField.setEnabled(false);

        if (!applicationIdTextField.getText().isEmpty()){
            
            this.selectedPet.setPetName(petNameTextField.getText());
            this.selectedPet.setAge(Integer.valueOf(ageTextField.getText()));
            this.selectedPet.setGender(genderTextField.getText());
            this.selectedPet.setPetType(petTypeTextField.getText());
            this.selectedPet.setBreed(breedTextField.getText());
            displayApplicantDetails();
        }
        else {
            JOptionPane.showMessageDialog(null, "Please make a selection");
        }
        
    }//GEN-LAST:event_updatePetButtonActionPerformed
 
    public void displayApplicantDetails() {
         
        ApplicantsDirectory appDirectory  = this.business.getAppDirectory();
       
        applicantTableModel.setRowCount(0);
       
        if (!appDirectory.getApplicantsDirectory().isEmpty()) {
            //display
            for(Applicant a: appDirectory.getApplicantsDirectory()) {
               //number of columns in the table = 9
               Object row[] = new Object[9];
               
               row[0] = a;
               //row[0] = a.getApplicationId();
               row[1] = a.getFirstName();
               row[2] = a.getLastName();
               row[3] = a.getDate();
               row[4] = a.getPetDetails().getPetName();
               row[5] = a.getPetDetails().getAge();
               row[6] = a.getPetDetails().getGender();
               row[7] = a.getPetDetails().getPetType();
               row[8] = a.getPetDetails().getBreed();
              
               //add row to the table
               this.applicantTableModel.addRow(row);
               System.out.println(a.getApplicationId());
            }
        }
        else{
           System.out.println("Empty list");
        }   
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreatePageHeaderLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JButton ViewButton;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTable applicantTable;
    private javax.swing.JLabel applicationDateLabel;
    private javax.swing.JLabel applicationIdLabel;
    private javax.swing.JTextField applicationIdTextField;
    private javax.swing.JLabel breedLabel;
    private javax.swing.JTextField breedTextField;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JButton deleteApplicantButton;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ownerFNameLabel;
    private javax.swing.JTextField ownerFNameTextField;
    private javax.swing.JLabel ownerLNameLabel;
    private javax.swing.JTextField ownerLNameTextField;
    private javax.swing.JLabel petHeaderLabel;
    private javax.swing.JLabel petNameLabel;
    private javax.swing.JTextField petNameTextField;
    private javax.swing.JLabel petTypeLabel;
    private javax.swing.JTextField petTypeTextField;
    private javax.swing.JButton updatePetButton;
    // End of variables declaration//GEN-END:variables

   
}
