/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import LibraryAppSystem.ApplicationSystem;
import LibraryAppSystem.Branch;
import LibraryAppSystem.UserAccount;
import LibraryAppSystem.UserAccountDirectory;
import javax.swing.JOptionPane;

/**
 *
 * @author mrunalipawar
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private ApplicationSystem applicationSystem;
    
    private UserAccountDirectory userAccountDirectory;
    
    private UserAccount userAccount;
    private Branch branch;
    
    public NewJFrame() {
        initComponents();
        this.applicationSystem = ApplicationSystem.getBusinessInstance();
        this.userAccountDirectory = applicationSystem.getUserAccountDirectory();
        populateDropdown();
    }

    public NewJFrame(ApplicationSystem applicationSystem, Branch branch, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);

        this.applicationSystem = applicationSystem;
        this.userAccount = userAccount;
        this.branch = branch;
        populateDropdown();
    }
    
    public void populateDropdown() {
        roleComboBox.removeAllItems();

        for (String role : this.applicationSystem.getUserAccountDirectory().getAllRoles()) {
            roleComboBox.addItem(role);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        roleComboBox = new javax.swing.JComboBox<>();
        headerLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jPanel1.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 189, 180, 40));

        passwordTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jPanel1.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 266, 180, 40));

        loginButton.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 397, 125, 41));

        jPanel1.add(roleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 335, 137, 36));

        headerLabel.setFont(new java.awt.Font("Kannada MN", 1, 24)); // NOI18N
        headerLabel.setText("WELCOME TO LIBRARY MANAGEMENT SYSTEMS");
        jPanel1.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 80, -1, 44));

        jLabel1.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 189, 119, 40));

        jLabel2.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 265, 119, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:

        String username = usernameTextField.getText();
        String password = passwordTextField.getText();
        String role = (String) roleComboBox.getSelectedItem();
        
        Boolean foundUser = false;
        
        if(this.applicationSystem.getUserAccountDirectory().authenticateUser(username, password) != null) {
            UserAccount user = this.applicationSystem.getUserAccountDirectory().authenticateUser(username, password);
            foundUser = true;
            user.getRole().getWorkArea(applicationSystem, branch, userAccount);
            this.setVisible(false);
        } else {
            for(Branch branch: this.applicationSystem.getBranchLists()) {
                if(branch.getBranchuseraccountDirectory().authenticateUser(username, password) != null) {
                    UserAccount branchUser = branch.getBranchuseraccountDirectory().authenticateUser(username, password);
                    foundUser = true;
                    branchUser.getRole().getWorkArea(applicationSystem, branch, userAccount);
                    this.setVisible(false);
                }
            }
        }
        // if user not found
        if(!foundUser) {
            JOptionPane.showMessageDialog(null, "Invalid Credentials");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
