/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.ChefDetails;
import Model.Contact;
import Model.FormFieldsValidation;
import Model.RecipeInfo;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mrunalipawar
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    private ChefDetails chefDetails;
    private Boolean emailValidate = false;
    private FormFieldsValidation formFieldVal;
    
    public CreateJPanel() {
        initComponents();
    }
    
    CreateJPanel(ChefDetails chefDetails) {
        initComponents();
        this.chefDetails = chefDetails;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createRecipeLabelHeader = new javax.swing.JLabel();
        chefFNameLabel = new javax.swing.JLabel();
        chefLNameLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        recipeLabel = new javax.swing.JLabel();
        recipeTitleLabel = new javax.swing.JLabel();
        noOfservingsLabel = new javax.swing.JLabel();
        isGlutenLabel = new javax.swing.JLabel();
        difficultyLevelLabel = new javax.swing.JLabel();
        noOfIngreLabel = new javax.swing.JLabel();
        categoryFoodLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        recipePictureLabel = new javax.swing.JLabel();
        imageJLabel = new javax.swing.JLabel();
        ChefFNameTextField = new javax.swing.JTextField();
        chefLNameTextField = new javax.swing.JTextField();
        userNameTextField = new javax.swing.JTextField();
        recipeTitleTextField = new javax.swing.JTextField();
        noOfservingsTextField = new javax.swing.JTextField();
        difficultyLevelTextField = new javax.swing.JTextField();
        noOfIngreTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryFoodList = new javax.swing.JList<>();
        descriptionTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        contactInfoLabel = new javax.swing.JLabel();
        emailIdLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        emailIdTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        glutenChoiceComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createRecipeLabelHeader.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        createRecipeLabelHeader.setText("CREATE RECIPE");
        add(createRecipeLabelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        chefFNameLabel.setText("Chef's First Name");
        add(chefFNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        chefLNameLabel.setText("Chef's Last Name");
        add(chefLNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        userNameLabel.setText("Username");
        add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 20));

        recipeLabel.setText("Recipe");
        add(recipeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 70, 20));

        recipeTitleLabel.setText("Recipe Title");
        add(recipeTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 80, -1));

        noOfservingsLabel.setText("No of Servings");
        add(noOfservingsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 277, -1, 20));

        isGlutenLabel.setText("is Gluten free");
        add(isGlutenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 317, -1, 20));

        difficultyLevelLabel.setText("Difficulty Level");
        add(difficultyLevelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, 30));

        noOfIngreLabel.setText("No of Ingredients");
        add(noOfIngreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        categoryFoodLabel.setText("Category of Food");
        add(categoryFoodLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        descriptionLabel.setText("Description");
        add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, 30));

        recipePictureLabel.setText("Recipe Picture");
        add(recipePictureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));
        add(imageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 150, 80));

        ChefFNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ChefFNameTextFieldKeyPressed(evt);
            }
        });
        add(ChefFNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 63, 160, 30));

        chefLNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chefLNameTextFieldKeyPressed(evt);
            }
        });
        add(chefLNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 103, 160, 30));

        userNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameTextFieldKeyPressed(evt);
            }
        });
        add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 143, 160, 30));
        add(recipeTitleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 223, 160, 30));
        add(noOfservingsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 160, 30));

        difficultyLevelTextField.setToolTipText("");
        add(difficultyLevelTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 160, 30));
        add(noOfIngreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 160, 30));

        categoryFoodList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Indian", "American", "Chinese", "Thai", "Mexican", "Italian" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        categoryFoodList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(categoryFoodList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 160, 110));
        add(descriptionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 160, 30));

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });
        add(browseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, -1, -1));

        contactInfoLabel.setText("Contact Information");
        add(contactInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        emailIdLabel.setText("Email ID");
        add(emailIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, -1, -1));

        phoneLabel.setText("Phone");
        add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 650, -1, 20));

        emailIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdTextFieldActionPerformed(evt);
            }
        });
        add(emailIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 180, 30));

        phoneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneTextFieldKeyPressed(evt);
            }
        });
        add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 180, 30));

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 710, -1, -1));

        glutenChoiceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        add(glutenChoiceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showDialog = browseImageFile.showOpenDialog(null);
        
        if(showDialog == JFileChooser.APPROVE_OPTION) {
            File selectedRecipeImageFile = browseImageFile.getSelectedFile();
            String fileLocationpath = selectedRecipeImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, fileLocationpath);
            
             //Displaying selected recipe image on JLabel 
             ImageIcon imgIcon = new ImageIcon(fileLocationpath);
             Image img = imgIcon.getImage().getScaledInstance(imageJLabel.getWidth(), imageJLabel.getHeight(), Image.SCALE_SMOOTH);
             //set the image as per the size of JLabel
             imageJLabel.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        String chefFName = ChefFNameTextField.getText();
        String chefLName = chefLNameTextField.getText();
        String chefUsername = userNameTextField.getText();
        
        if(chefFName.equals("") && chefLName.equals("") && chefUsername.equals("")){
            JOptionPane.showMessageDialog(this, "Enter Chef Details");
        }
        else if(!chefFName.equals("") && chefLName.equals("") && chefUsername.equals("")){
             JOptionPane.showMessageDialog(this, "Enter Chef's First Name");
        }
        else if(chefFName.equals("") && !chefLName.equals("") && chefUsername.equals("")){
             JOptionPane.showMessageDialog(this, "Enter Chef's Last Namme");
        }
        else if(chefFName.equals("") && chefLName.equals("") && !chefUsername.equals("")){
             JOptionPane.showMessageDialog(this, "Enter Chef's Username");
        }
      
        String emailId = emailIdTextField.getText();
        long phoneNum = Long.valueOf(phoneTextField.getText());
        
        this.chefDetails.setFirstName(chefFName);
        this.chefDetails.setLastName(chefLName);
        this.chefDetails.setUserName(chefUsername);
        
       
        String recipeTitle = recipeTitleTextField.getText();
        RecipeInfo recipeInfo = this.chefDetails.getRecipeInfo();
        recipeInfo.setRecipeTitle(recipeTitle);
        recipeInfo.setNoOfServings(Integer.parseInt(noOfservingsTextField.getText()));
        recipeInfo.setGlutenFreeChoice(Boolean.valueOf(this.glutenChoiceResponse()));
        //(Boolean.valueOf(glutenChoiceComboBox.getSelectedItem().toString()));
        recipeInfo.setDifficultyLevel(Double.valueOf(difficultyLevelTextField.getText()));
        recipeInfo.setNoOfIngredients(Integer.parseInt(noOfIngreTextField.getText()));
        recipeInfo.setCategory(categoryFoodList.getSelectedValue());
        recipeInfo.setDescription(descriptionTextField.getText());
        
        Contact contact = this.chefDetails.getContactDetails();
        contact.setEmailId(emailId);
        contact.setPhoneNo(phoneNum);
       
        JOptionPane.showMessageDialog(null, "CREATED SUCCESSFULLY!");
    }//GEN-LAST:event_createButtonActionPerformed

    private void ChefFNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ChefFNameTextFieldKeyPressed
        // TODO add your handling code here:
        //Field only accepting alphabets whitespace and backspace key delete
        char ch = evt.getKeyChar();
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch)) {
            ChefFNameTextField.setEditable(true);
        }
        else{
            ChefFNameTextField.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter valid Name");
        }
        
    }//GEN-LAST:event_ChefFNameTextFieldKeyPressed

    private void chefLNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chefLNameTextFieldKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch)) {
            chefLNameTextField.setEditable(true);
        }
        else{
            chefLNameTextField.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter valid Name");
        }
        
    }//GEN-LAST:event_chefLNameTextFieldKeyPressed

    private void userNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTextFieldKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch)) {
            userNameTextField.setEditable(true);
        }
        else{
            userNameTextField.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter valid Username");
        }
        
    }//GEN-LAST:event_userNameTextFieldKeyPressed

    private void phoneTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTextFieldKeyPressed
        // TODO add your handling code here:
        String phoneNo = phoneTextField.getText();
        int len = phoneNo.length();
        
        char c = evt.getKeyChar();
        
        if(c >='0' && c<='9'){
            if(len<10){
                phoneTextField.setEditable(true);
            }
            else{
                phoneTextField.setEditable(false);
                JOptionPane.showMessageDialog(this, "Enter valid phone no");
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                phoneTextField.setEditable(true);
            }
            else{
                phoneTextField.setEditable(false);
            }
        }
    }//GEN-LAST:event_phoneTextFieldKeyPressed

    private void emailIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdTextFieldActionPerformed
        // TODO add your handling code here:
        emailValidate = formFieldVal.isValidEmail(emailIdTextField.getText());
         if(!emailValidate) {
            JOptionPane.showMessageDialog(null, "Please Enter valid email");
        } else {
            System.out.println("Email Validated successfully");
        }
    }//GEN-LAST:event_emailIdTextFieldActionPerformed

    
    
    public String glutenChoiceResponse() {
        
         String choice = (String) glutenChoiceComboBox.getSelectedItem();
         
            if(choice.equalsIgnoreCase("Yes")) {
                //display the product content
                System.out.println("Selected yes in response -----"+choice);
                
                return choice;
            }
            else{
                return "No";
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChefFNameTextField;
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel categoryFoodLabel;
    private javax.swing.JList<String> categoryFoodList;
    private javax.swing.JLabel chefFNameLabel;
    private javax.swing.JLabel chefLNameLabel;
    private javax.swing.JTextField chefLNameTextField;
    private javax.swing.JLabel contactInfoLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel createRecipeLabelHeader;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel difficultyLevelLabel;
    private javax.swing.JTextField difficultyLevelTextField;
    private javax.swing.JLabel emailIdLabel;
    private javax.swing.JTextField emailIdTextField;
    private javax.swing.JComboBox<String> glutenChoiceComboBox;
    private javax.swing.JLabel imageJLabel;
    private javax.swing.JLabel isGlutenLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel noOfIngreLabel;
    private javax.swing.JTextField noOfIngreTextField;
    private javax.swing.JLabel noOfservingsLabel;
    private javax.swing.JTextField noOfservingsTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel recipeLabel;
    private javax.swing.JLabel recipePictureLabel;
    private javax.swing.JLabel recipeTitleLabel;
    private javax.swing.JTextField recipeTitleTextField;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
