/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.ChefDetails;

/**
 *
 * @author mrunalipawar
 */
public class MyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyJFrame
     */
    
    private ChefDetails chefDetails;
    public MyJFrame() {
        initComponents();
        this.chefDetails = new ChefDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        DisplayJPanel = new javax.swing.JPanel();
        ControlJPanel = new javax.swing.JPanel();
        createMainButton = new javax.swing.JButton();
        readMainButton = new javax.swing.JButton();
        updateMainButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DisplayJPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout DisplayJPanelLayout = new javax.swing.GroupLayout(DisplayJPanel);
        DisplayJPanel.setLayout(DisplayJPanelLayout);
        DisplayJPanelLayout.setHorizontalGroup(
            DisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        DisplayJPanelLayout.setVerticalGroup(
            DisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(DisplayJPanel);

        ControlJPanel.setBackground(new java.awt.Color(204, 204, 255));

        createMainButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        createMainButton.setText("Create");
        createMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMainButtonActionPerformed(evt);
            }
        });

        readMainButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        readMainButton.setText("Read");
        readMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readMainButtonActionPerformed(evt);
            }
        });

        updateMainButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        updateMainButton.setText("Update");
        updateMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlJPanelLayout = new javax.swing.GroupLayout(ControlJPanel);
        ControlJPanel.setLayout(ControlJPanelLayout);
        ControlJPanelLayout.setHorizontalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createMainButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(readMainButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateMainButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        ControlJPanelLayout.setVerticalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(createMainButton)
                .addGap(26, 26, 26)
                .addComponent(readMainButton)
                .addGap(31, 31, 31)
                .addComponent(updateMainButton)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(ControlJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMainButtonActionPerformed
        // TODO add your handling code here:
        
        CreateJPanelForm createJPanelForm = new CreateJPanelForm(chefDetails);
        jSplitPane1.setRightComponent(createJPanelForm);
    }//GEN-LAST:event_createMainButtonActionPerformed

    private void readMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readMainButtonActionPerformed
        // TODO add your handling code here:
        
        ReadJPanelForm readJPanelForm = new ReadJPanelForm(chefDetails);
        jSplitPane1.setRightComponent(readJPanelForm);
    }//GEN-LAST:event_readMainButtonActionPerformed

    private void updateMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMainButtonActionPerformed
        // TODO add your handling code here:
        UpdateJPanelForm updateJPanelForm = new UpdateJPanelForm(chefDetails);
        jSplitPane1.setRightComponent(updateJPanelForm);
    }//GEN-LAST:event_updateMainButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlJPanel;
    private javax.swing.JPanel DisplayJPanel;
    private javax.swing.JButton createMainButton;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton readMainButton;
    private javax.swing.JButton updateMainButton;
    // End of variables declaration//GEN-END:variables
}
