/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.ChefDetails;
import Model.Contact;
import Model.RecipeInfo;
import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author mrunalipawar
 */
public class ReadJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReadJPanel
     */
     private ChefDetails chefDetails;
    
    public ReadJPanel() {
        initComponents();
    }
    
    ReadJPanel(ChefDetails chefDetails) {
        initComponents();
        this.chefDetails = chefDetails;
        displayPackageDetails();
    }
    
     public void displayPackageDetails() {
        
         ChefFNameTextField.setText(this.chefDetails.getFirstName());
         chefLNameTextField.setText(this.chefDetails.getLastName());
         userNameTextField.setText(this.chefDetails.getUserName());
         
         RecipeInfo recipeInfo = this.chefDetails.getRecipeInfo();
         recipeTitleTextField.setText(recipeInfo.getRecipeTitle());
         noOfservingsTextField.setText(String.valueOf(recipeInfo.getNoOfServings()));
       
         
         glutenFreeTextField.setText(String.valueOf(recipeInfo.isGlutenFreeChoice()));
         difficultyLevelTextField.setText(String.valueOf(recipeInfo.getDifficultyLevel()));
         noOfIngreTextField.setText(String.valueOf(recipeInfo.getNoOfIngredients()));
         categoryFoodTextField.setText(recipeInfo.getCategory());
         descriptionTextField.setText(recipeInfo.getDescription());
         
         /*JFileChooser browseImageFile = new JFileChooser();
         File selectedRecipeImageFile = browseImageFile.getSelectedFile();
         String fileLocationpath = selectedRecipeImageFile.getAbsolutePath();
         System.out.println("Filepath : "+ fileLocationpath);*/
            
         //Displaying selected recipe image on JLabel
         ImageIcon imgIcon = new ImageIcon("/Users/mrunalipawar/Documents/images.jpeg");
         Image img = imgIcon.getImage();
                 //.getScaledInstance(imageJLabel.getWidth(), imageJLabel.getHeight(), Image.SCALE_SMOOTH);
         //set the image as per the size of JLabel
         imageJLabel.setIcon(new ImageIcon(img)); 
         
         Contact contact = this.chefDetails.getContactDetails();
         emailIdTextField.setText(contact.getEmailId());
         phoneTextField.setText(String.valueOf(contact.getPhoneNo()));
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        readRecipeLabelHeader = new javax.swing.JLabel();
        chefFNameLabel = new javax.swing.JLabel();
        chefLNameLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        recipeLabel = new javax.swing.JLabel();
        recipeTitleLabel = new javax.swing.JLabel();
        noOfservingsLabel = new javax.swing.JLabel();
        isGlutenLabel = new javax.swing.JLabel();
        difficultyLevelLabel = new javax.swing.JLabel();
        noOfIngreLabel = new javax.swing.JLabel();
        categoryFoodLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        recipePictureLabel = new javax.swing.JLabel();
        imageJLabel = new javax.swing.JLabel();
        ChefFNameTextField = new javax.swing.JTextField();
        chefLNameTextField = new javax.swing.JTextField();
        userNameTextField = new javax.swing.JTextField();
        recipeTitleTextField = new javax.swing.JTextField();
        noOfservingsTextField = new javax.swing.JTextField();
        difficultyLevelTextField = new javax.swing.JTextField();
        noOfIngreTextField = new javax.swing.JTextField();
        descriptionTextField = new javax.swing.JTextField();
        contactInfoLabel = new javax.swing.JLabel();
        emailIdLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        emailIdTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        categoryFoodTextField = new javax.swing.JTextField();
        glutenFreeTextField = new javax.swing.JTextField();
        categoryFoodTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        readRecipeLabelHeader.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        readRecipeLabelHeader.setText("READ RECIPE");
        add(readRecipeLabelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        chefFNameLabel.setText("Chef's First Name");
        add(chefFNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        chefLNameLabel.setText("Chef's Last Name");
        add(chefLNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        userNameLabel.setText("Username");
        add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 20));

        recipeLabel.setText("Recipe");
        add(recipeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 70, 20));

        recipeTitleLabel.setText("Recipe Title");
        add(recipeTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 80, -1));

        noOfservingsLabel.setText("No of Servings");
        add(noOfservingsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        isGlutenLabel.setText("is Gluten free");
        add(isGlutenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        difficultyLevelLabel.setText("Difficulty Level");
        add(difficultyLevelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, 30));

        noOfIngreLabel.setText("No of Ingredients");
        add(noOfIngreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, 30));

        categoryFoodLabel.setText("Category of Food");
        add(categoryFoodLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        descriptionLabel.setText("Description");
        add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 280, 70, 30));

        recipePictureLabel.setText("Recipe Picture");
        add(recipePictureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));
        add(imageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 160, 80));
        add(ChefFNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, 30));
        add(chefLNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, 30));
        add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, 30));
        add(recipeTitleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 223, 160, 30));
        add(noOfservingsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 160, 30));

        difficultyLevelTextField.setToolTipText("");
        add(difficultyLevelTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 160, 30));
        add(noOfIngreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 160, 30));
        add(descriptionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 160, 30));

        contactInfoLabel.setText("Contact Information");
        add(contactInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        emailIdLabel.setText("Email ID");
        add(emailIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, -1));

        phoneLabel.setText("Phone");
        add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, -1, 20));
        add(emailIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 180, 30));
        add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 180, 30));
        add(categoryFoodTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 150, 30));
        add(glutenFreeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 313, 160, 30));
        add(categoryFoodTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 150, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChefFNameTextField;
    private javax.swing.JLabel categoryFoodLabel;
    private javax.swing.JTextField categoryFoodTextField;
    private javax.swing.JTextField categoryFoodTextField1;
    private javax.swing.JLabel chefFNameLabel;
    private javax.swing.JLabel chefLNameLabel;
    private javax.swing.JTextField chefLNameTextField;
    private javax.swing.JLabel contactInfoLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel difficultyLevelLabel;
    private javax.swing.JTextField difficultyLevelTextField;
    private javax.swing.JLabel emailIdLabel;
    private javax.swing.JTextField emailIdTextField;
    private javax.swing.JTextField glutenFreeTextField;
    private javax.swing.JLabel imageJLabel;
    private javax.swing.JLabel isGlutenLabel;
    private javax.swing.JLabel noOfIngreLabel;
    private javax.swing.JTextField noOfIngreTextField;
    private javax.swing.JLabel noOfservingsLabel;
    private javax.swing.JTextField noOfservingsTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel readRecipeLabelHeader;
    private javax.swing.JLabel recipeLabel;
    private javax.swing.JLabel recipePictureLabel;
    private javax.swing.JLabel recipeTitleLabel;
    private javax.swing.JTextField recipeTitleTextField;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
