/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerWorkArea;

import Books.Book;
import Customer.Customer;
import General.Magazine;
import Librarian.Librarian;
import LibraryAppSystem.ApplicationSystem;
import Librarian.Branch;
import LibraryAppSystem.UserAccount;
import Materials.Material;
import Services.RentalRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mrunalipawar
 */
public class CustomerOrderRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerOrderRequestJPanel
     */
    
    private ApplicationSystem applicationSystem;
    private UserAccount userAccount;
    private Branch branch;
   
    public CustomerOrderRequestJPanel() {
        initComponents();
    }
    
    public CustomerOrderRequestJPanel(ApplicationSystem applicationSystem, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
        this.applicationSystem = applicationSystem;
        //this.branch = branch;
        this.userAccount = userAccount;
      
        selectBranchJLabel.setText(userAccount.getUsername());
        populateBranchLocations();
        populateBranchLibrary();
        populateMaterialName();
        populateData();
    }
   


    public void populateBranchLocations(){
        ArrayList<Branch> branchList= this.applicationSystem.getBranchLists();
        for(Branch b:branchList){
            branchLocationComboBox.addItem(b.getLibrarian().getLocation());
        }
        
    }
    
    public void populateBranchLibrary(){
        libraryComboBox.removeAllItems();
        ArrayList<Branch> branchList= this.applicationSystem.getBranchLists();
        String locSelected =(String) branchLocationComboBox.getSelectedItem();
        for(Branch b:branchList){
            if(b.getLibrarian().getLocation().equals(locSelected)){
                libraryComboBox.addItem(b.getLibrarian());
            }
        } 
    }
    
    public void populateData(){
        Librarian lib = (Librarian) libraryComboBox.getSelectedItem();
        String materialSelected = (String) chooseComboBox.getSelectedItem();
        ArrayList<Book> bookList= lib.getBooksDirectory().getBooklists();
        ArrayList<Magazine> magList= lib.getMagazineDirectory().getMagazinelist();
         if(materialSelected.equals("Book")){
            materialsComboBox.removeAllItems();
            for(Book b:bookList){
                if(b.isIsAvailablityFlag()){
                  materialsComboBox.addItem(b);
                }
            }    
        }
        else{
            materialsComboBox.removeAllItems();
            for(Magazine m:magList){
                if(m.isIsAvailablityFlag()){
                  materialsComboBox.addItem(m);
                }
            }
        }
        
    }
    public void populateMaterialName(){
        Material materialSelected =(Material) materialsComboBox.getSelectedItem();
        if(materialSelected!=null){
            materialNameField.setText(materialSelected.getName());
        }
        else{
            materialNameField.setText("");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookOrderButton = new javax.swing.JButton();
        selectBranchJLabel = new javax.swing.JLabel();
        branchLocationComboBox = new javax.swing.JComboBox<>();
        selectBranchJLabel1 = new javax.swing.JLabel();
        libraryComboBox = new javax.swing.JComboBox();
        chooseComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        materialsComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        materialNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        durationComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        AuthorHeaderjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookOrderButton.setText("SUBMIT ORDER");
        bookOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookOrderButtonActionPerformed(evt);
            }
        });
        add(bookOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 130, 33));

        selectBranchJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        selectBranchJLabel.setText("Select Branch");
        add(selectBranchJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 30));

        branchLocationComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                branchLocationComboBoxItemStateChanged(evt);
            }
        });
        add(branchLocationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 140, 30));

        selectBranchJLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        selectBranchJLabel1.setText("Select Library");
        add(selectBranchJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 100, 30));

        add(libraryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 140, 30));

        chooseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book", "Magazine" }));
        chooseComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chooseComboBoxItemStateChanged(evt);
            }
        });
        chooseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseComboBoxActionPerformed(evt);
            }
        });
        add(chooseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 180, 30));

        jLabel1.setText("Material Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        materialsComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                materialsComboBoxItemStateChanged(evt);
            }
        });
        add(materialsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 180, 30));

        jLabel2.setText("Material Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        add(materialNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 180, 30));

        jLabel3.setText("Choose material:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        durationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "weekly", "monthly", "quaterly" }));
        add(durationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 180, 30));

        jLabel4.setText("Duration");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 30));

        AuthorHeaderjLabel.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        AuthorHeaderjLabel.setText("LIBRARY MANAGEMENT SYSTEM - CUSTOMER ORDER PORTAL");
        add(AuthorHeaderjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bookOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookOrderButtonActionPerformed
        // TODO add your handling code here:
        
        Librarian lib = (Librarian) libraryComboBox.getSelectedItem();
        String materialSelected =(String) chooseComboBox.getSelectedItem();
        Material mat =(Material) materialsComboBox.getSelectedItem();
        String duration= (String) durationComboBox.getSelectedItem();
        mat.setIsAvailablityFlag(false);
        Customer c = this.applicationSystem.getCustomerDirectory().findById(userAccount.getAccountId());
        RentalRequest request = c.getMasterRentalRequestDirectory().createOrder(c, mat, "Requested", duration, materialSelected,lib);
        JOptionPane.showMessageDialog(null, "Request Created.");
        
        populateData();
        populateMaterialName();
    }//GEN-LAST:event_bookOrderButtonActionPerformed

    private void chooseComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chooseComboBoxItemStateChanged
        // TODO add your handling code here:
        populateData();
    }//GEN-LAST:event_chooseComboBoxItemStateChanged

    private void chooseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseComboBoxActionPerformed

    private void materialsComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_materialsComboBoxItemStateChanged
        // TODO add your handling code here:
        populateMaterialName();
    }//GEN-LAST:event_materialsComboBoxItemStateChanged

    private void branchLocationComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_branchLocationComboBoxItemStateChanged
        // TODO add your handling code here:
        populateBranchLibrary();
        populateMaterialName();
        populateData();
    }//GEN-LAST:event_branchLocationComboBoxItemStateChanged

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorHeaderjLabel;
    private javax.swing.JButton bookOrderButton;
    private javax.swing.JComboBox<String> branchLocationComboBox;
    private javax.swing.JComboBox<String> chooseComboBox;
    private javax.swing.JComboBox durationComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox libraryComboBox;
    private javax.swing.JTextField materialNameField;
    private javax.swing.JComboBox materialsComboBox;
    private javax.swing.JLabel selectBranchJLabel;
    private javax.swing.JLabel selectBranchJLabel1;
    // End of variables declaration//GEN-END:variables
}
