/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LibrarianWorkArea;

import LibraryAppSystem.ApplicationSystem;
import LibraryAppSystem.UserAccount;
import BookAuthor.Author;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrunalipawar
 */
public class AuthorManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AuthorManagementJPanel
     */
    
    private ApplicationSystem applicationSystem;
    private UserAccount userAccount;
    DefaultTableModel tableModel;
    public AuthorManagementJPanel() {
        initComponents();
    }

    AuthorManagementJPanel(ApplicationSystem applicationSystem, UserAccount userAccount) {
       
        initComponents();
        this.applicationSystem = applicationSystem;
        this.userAccount= userAccount;
        this.tableModel = (DefaultTableModel)Jtable.getModel();
        //populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable = new javax.swing.JTable();
        addAuthorButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, -1));

        Jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Author Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Jtable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 170, 200));

        addAuthorButton.setText("ADD AUTHOR");
        addAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorButtonActionPerformed(evt);
            }
        });
        add(addAuthorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthorButtonActionPerformed
        // TODO add your handling code here:
        Author g = this.applicationSystem.getAuthorDirectory().createAuthor(nameTextField.getText());
        populate();
    }//GEN-LAST:event_addAuthorButtonActionPerformed

     public void populate() {
        tableModel.setRowCount(0);
        for (Author b : this.applicationSystem.getAuthorDirectory().getAuthorDirectory()) {
            //UserAccount u = this.applicationSystem.getUserAccountDirectory().findbyId(b.getBookName());
            Object[] row = new Object[1];
            row[0] = b.getName();
            tableModel.addRow(row);  
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtable;
    private javax.swing.JButton addAuthorButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
}
