/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LibrarianWorkArea;

import LibraryAppSystem.ApplicationSystem;
import LibraryAppSystem.UserAccount;
import BookAuthor.Author;
import Librarian.Librarian;
import LibraryAppSystem.Branch;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrunalipawar
 */
public class AuthorManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AuthorManagementJPanel
     */
    
    private ApplicationSystem applicationSystem;
    private UserAccount userAccount;
    private Branch branch;
    private Librarian librarian;
    DefaultTableModel tableModel;
    public AuthorManagementJPanel() {
        initComponents();
    }

    AuthorManagementJPanel(ApplicationSystem applicationSystem,UserAccount userAccount, Librarian librarian) {
       
        initComponents();
        this.setVisible(true);
        this.applicationSystem = applicationSystem;
        this.branch = branch;
        this.librarian = librarian;
        this.userAccount= userAccount;
        this.tableModel = (DefaultTableModel)Jtable.getModel();
        populateAuthorCatelog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authorBioTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable = new javax.swing.JTable();
        addAuthorButton = new javax.swing.JButton();
        authorNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AuthorHeaderjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(authorBioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 130, 30));

        Jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Author Name", "Author Bio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Jtable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 240, 200));

        addAuthorButton.setText("ADD AUTHOR");
        addAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorButtonActionPerformed(evt);
            }
        });
        add(addAuthorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 40));
        add(authorNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, 30));

        jLabel1.setText("Author Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 30));

        jLabel2.setText("Author Bio");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 70, 30));

        AuthorHeaderjLabel.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        AuthorHeaderjLabel.setText("LIBRARY MANAGEMENT SYSTEM - AUTHORS CATELOG");
        add(AuthorHeaderjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthorButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<Author> authors=this.librarian.getAuthorDirectory().getAuthorsList();
            if(authors.isEmpty()){
                    this.librarian.getAuthorDirectory().createAuthor(authorNameTextField.getText(),authorBioTextField.getText());
                    JOptionPane.showMessageDialog(null, "Author Created.");
                    populateAuthorCatelog();   
            }else{
               for(Author auth : authors){
                 if(auth.getAuthorName()!=authorNameTextField.getText()){
                    this.librarian.getAuthorDirectory().createAuthor(authorNameTextField.getText(),authorBioTextField.getText());
                    JOptionPane.showMessageDialog(null, "Author Created.");
                    populateAuthorCatelog(); 
                 }
               } 
            }
    }//GEN-LAST:event_addAuthorButtonActionPerformed

     public void populateAuthorCatelog() {
        tableModel.setRowCount(0);
        for (Author a : this.librarian.getAuthorDirectory().getAuthorsList()) {
            Object[] row = new Object[2];
            row[0] = a.getAuthorName();
            row[1] = a.getAuthorBio();
            tableModel.addRow(row);  
        }
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorHeaderjLabel;
    private javax.swing.JTable Jtable;
    private javax.swing.JButton addAuthorButton;
    private javax.swing.JTextField authorBioTextField;
    private javax.swing.JTextField authorNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
