/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LibrarianWorkArea;

import LibraryAppSystem.ApplicationSystem;
import LibraryAppSystem.UserAccount;
import BookAuthor.Author;
import BookGenre.Genre;
import Books.BooksDirectory;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrunalipawar
 */
public class BookManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookManagementJPanel
     */
    
    private ApplicationSystem applicationSystem;
    private UserAccount userAccount;
    DefaultTableModel tableModel;
    
    public BookManagementJPanel() {
        initComponents();
    }

    BookManagementJPanel(ApplicationSystem applicationSystem, UserAccount userAccount) {
        initComponents();
        this.applicationSystem = applicationSystem;
        this.userAccount= userAccount;
        this.tableModel = (DefaultTableModel)bookCatelogJtable.getModel();
        populateAuthorDetails();
        populateGenreDetails();
    }
    
    public void populateAuthorDetails () {
        authorComboBox.removeAllItems();
        
        for(Author p: this.applicationSystem.getAuthorDirectory().getAuthorDirectory()){
           // authorComboBox.addItem(p);
        }
    }
    
    public void populateGenreDetails () {
        genreComboBox.removeAllItems();
        
        for(Genre g : this.applicationSystem.getGenreDirectory().getGenreDirectory()){
           // authorComboBox.addItem(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        booknameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookCatelogJtable = new javax.swing.JTable();
        addBookButton = new javax.swing.JButton();
        authorComboBox = new javax.swing.JComboBox<>();
        genreComboBox = new javax.swing.JComboBox<>();
        booknameTextField1 = new javax.swing.JTextField();
        booknameTextField2 = new javax.swing.JTextField();
        bookNamejLabel = new javax.swing.JLabel();
        noOfPagesjLabel = new javax.swing.JLabel();
        languagejLabel = new javax.swing.JLabel();
        authorNamejLabel = new javax.swing.JLabel();
        genreNameLabel = new javax.swing.JLabel();
        typeOfBindingjLabel = new javax.swing.JLabel();
        booknameTextField3 = new javax.swing.JTextField();
        AuthorHeaderjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(booknameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 170, 30));

        bookCatelogJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Book Name", "No of Pages", "Language", "Type Of Binding", "Author Name", "Genre Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookCatelogJtable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 650, 210));

        addBookButton.setText("ADD BOOK");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });
        add(addBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, 30));

        add(authorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 170, 30));

        add(genreComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 170, 30));
        add(booknameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 170, 30));
        add(booknameTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, 30));

        bookNamejLabel.setText("Book Name");
        add(bookNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 127, -1, 30));

        noOfPagesjLabel.setText("No Of Pages");
        add(noOfPagesjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 187, -1, 20));

        languagejLabel.setText("Language");
        add(languagejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        authorNamejLabel.setText("Author Name");
        add(authorNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        genreNameLabel.setText("Genre Name");
        add(genreNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, 20));

        typeOfBindingjLabel.setText("Type Of Binding");
        add(typeOfBindingjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 30));
        add(booknameTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 170, 30));

        AuthorHeaderjLabel.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        AuthorHeaderjLabel.setText("LIBRARY MANAGEMENT SYSTEM - BOOK CATELOG ");
        add(AuthorHeaderjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
        // TODO add your handling code here:
        BooksDirectory ua = this.applicationSystem.getBookDirectory();
        
        //Book b = this.applicationSystem.getBookDirectory().CreateBook(booknameTextField.getText());
           // populate();
        
    }//GEN-LAST:event_addBookButtonActionPerformed

    /*public void populate() {
        tableModel.setRowCount(0);
        for (Book b : this.applicationSystem.getBookDirectory().getBookDirectory()) {
            //UserAccount u = this.applicationSystem.getUserAccountDirectory().findbyId(b.getBookName());
            Object[] row = new Object[3];
            row[0] = b.getBookName();
            row[1] = b.getAuthor();
            row[2] = b.getGenre();
            tableModel.addRow(row);
            
        }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorHeaderjLabel;
    private javax.swing.JButton addBookButton;
    private javax.swing.JComboBox<String> authorComboBox;
    private javax.swing.JLabel authorNamejLabel;
    private javax.swing.JTable bookCatelogJtable;
    private javax.swing.JLabel bookNamejLabel;
    private javax.swing.JTextField booknameTextField;
    private javax.swing.JTextField booknameTextField1;
    private javax.swing.JTextField booknameTextField2;
    private javax.swing.JTextField booknameTextField3;
    private javax.swing.JComboBox<String> genreComboBox;
    private javax.swing.JLabel genreNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel languagejLabel;
    private javax.swing.JLabel noOfPagesjLabel;
    private javax.swing.JLabel typeOfBindingjLabel;
    // End of variables declaration//GEN-END:variables
}
