/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LibrarianWorkArea;

import LibraryAppSystem.ApplicationSystem;
import LibraryAppSystem.UserAccount;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrunalipawar
 */
public class MagazineManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MagazineManagementJPanel
     */
    private ApplicationSystem applicationSystem;
    private UserAccount userAccount;
    DefaultTableModel tableModel;
    public MagazineManagementJPanel() {
        initComponents();
    }

    MagazineManagementJPanel(ApplicationSystem applicationSystem, UserAccount userAccount) {
       
        initComponents();
        this.applicationSystem = applicationSystem;
        this.userAccount= userAccount;
       // this.tableModel = (DefaultTableModel)Jtable.getModel();
        //populate();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comapnyNamejLabel = new javax.swing.JLabel();
        issueTypejLabel = new javax.swing.JLabel();
        companyNameTextField = new javax.swing.JTextField();
        issueTypeComboBox = new javax.swing.JComboBox<>();
        addMagazineButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AuthorHeaderjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comapnyNamejLabel.setText("Company Name");
        add(comapnyNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        issueTypejLabel.setText("Issue Type");
        add(issueTypejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 157, -1, 20));
        add(companyNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 100, 30));

        issueTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weekly", "Fortnightly" }));
        add(issueTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, 30));

        addMagazineButton.setText("ADD MAGAZINE");
        add(addMagazineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Company Name", "IssueType"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 370, 190));

        AuthorHeaderjLabel.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        AuthorHeaderjLabel.setText("LIBRARY MANAGEMENT SYSTEM - MAGAZINE CATELOG");
        add(AuthorHeaderjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 30, 580, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorHeaderjLabel;
    private javax.swing.JButton addMagazineButton;
    private javax.swing.JLabel comapnyNamejLabel;
    private javax.swing.JTextField companyNameTextField;
    private javax.swing.JComboBox<String> issueTypeComboBox;
    private javax.swing.JLabel issueTypejLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
